"""empty message

Revision ID: 13a7301da16
Revises: 3bccd7c959
Create Date: 2015-10-25 00:26:56.207164

"""

# revision identifiers, used by Alembic.
revision = '13a7301da16'
down_revision = '3bccd7c959'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chasm_config', sa.Column('gui_visible', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chasm_config', 'gui_visible')
    ### end Alembic commands ###
