"""empty message

Revision ID: 1b66d5ac7a1
Revises: None
Create Date: 2015-10-24 18:16:19.566633

"""

# revision identifiers, used by Alembic.
revision = '1b66d5ac7a1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurations', sa.Column('remark', sa.String(length=1000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configurations', 'remark')
    ### end Alembic commands ###
