"""empty message

Revision ID: 1e5ecbfd28f
Revises: 13a7301da16
Create Date: 2015-10-25 00:55:43.126343

"""

# revision identifiers, used by Alembic.
revision = '1e5ecbfd28f'
down_revision = '13a7301da16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configurations')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subversion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('branding', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remark', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='configurations_pkey')
    )
    ### end Alembic commands ###
