"""empty message

Revision ID: 3bccd7c959
Revises: 10bfefbfff8
Create Date: 2015-10-24 23:48:45.869199

"""

# revision identifiers, used by Alembic.
revision = '3bccd7c959'
down_revision = '10bfefbfff8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chasm_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('config')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('parameter', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='config_pkey')
    )
    op.drop_table('chasm_config')
    ### end Alembic commands ###
